### PR TITLE
Add `talksabout("something")` feature

### PR DESCRIPTION
**Pull request by roflmaostc**
As discussed in #38 

```julia
julia> JuliaCon.talksabout("causal")

Thursday 11 July 2024, 16:30 in Else (1.3)
        Causal Forecasting: How to disentangle causal effects (Talk)
        ├─ 
        ├─ https://pretalx.com/juliacon2024/talk/QZZQLF/
        └─ PyData

Thursday 11 July 2024, 14:00 in Method (1.5)
        Recursive Causal Discovery with Julia (Lightning Talk)
        ├─ Sepehr Elahi
        ├─ https://pretalx.com/juliacon2024/talk/FYFNAR/
        └─ General

Friday 12 July 2024, 11:00 in For Loop (3.2)
        Causal Machine Learning with CausalELM (Talk)
        ├─ Darren Colby
        ├─ https://pretalx.com/juliacon2024/talk/J9D8PL/
        └─ AI/ML/AD

(Shown times are in the following time zone: Europe/Berlin)

```

### CODE REVIEW

**Comment by roflmaostc** [comment]
bump, next JuliaCon is coming soon™

**Comment by carstenbauer** [comment]
LGTM. The only thing that might be slightly deceptive is that `talksabout` doesn't scan the abstract of the talk (as one might naively think).

**Comment by roflmaostc** [comment]
The abstract is not stored in the dataframe yet, right?

**Comment by carstenbauer** [comment]
No it's not. But we could store it in it.

**Pull request merged**
