### PR TITLE
Include abstract to the dataframe

### PR DESCRIPTION
**Pull request by roflmaostc**
I guess non-breaking if we assume the dataframe was internal.

```julia
julia> JuliaCon.talksabout("wave")

Wednesday 10 July 2024, 10:50 in If (1.1)
        MIToS Evolution: Riding the Bioinformatics Wave (Lightning Talk)
        ├─ Diego Javier Zea
        ├─ https://pretalx.com/juliacon2024/talk/RM9TMC/
        └─ Biology & Life Sciences

Friday 12 July 2024, 16:24 in Function (4.1)
        SeismicWaves.jl: a wave simulation package for FWI on multi-xPUs (Talk)
        ├─ Giacomo Aloisi
        ├─ https://pretalx.com/juliacon2024/talk/TGQYQX/
        └─ Julia for High-Performance Computing

Friday 12 July 2024, 16:00 in For Loop (3.2)
        Wave and Ray Optics for Light Based Tomographic 3D printing (Talk)
        ├─ Felix Wechsler
        ├─ https://pretalx.com/juliacon2024/talk/WEXWEJ/
        └─ Physics & Quantum Chemistry

Friday 12 July 2024, 14:30 in While Loop (4.2)
        High Resolution Flux Estimation with TurbulenceFlux.jl (Lightning Talk)
        ├─ Gabriel Destouet
        ├─ https://pretalx.com/juliacon2024/talk/7LAYTN/
        └─ Earth and climate science in Julia: Power to the user

(Shown times are in the following time zone: Europe/Berlin)

julia> JuliaCon.talksabout("wave"; search_abstract=false)

Wednesday 10 July 2024, 10:50 in If (1.1)
        MIToS Evolution: Riding the Bioinformatics Wave (Lightning Talk)
        ├─ Diego Javier Zea
        ├─ https://pretalx.com/juliacon2024/talk/RM9TMC/
        └─ Biology & Life Sciences

Friday 12 July 2024, 16:24 in Function (4.1)
        SeismicWaves.jl: a wave simulation package for FWI on multi-xPUs (Talk)
        ├─ Giacomo Aloisi
        ├─ https://pretalx.com/juliacon2024/talk/TGQYQX/
        └─ Julia for High-Performance Computing

Friday 12 July 2024, 16:00 in For Loop (3.2)
        Wave and Ray Optics for Light Based Tomographic 3D printing (Talk)
        ├─ Felix Wechsler
        ├─ https://pretalx.com/juliacon2024/talk/WEXWEJ/
        └─ Physics & Quantum Chemistry

(Shown times are in the following time zone: Europe/Berlin)

```

### CODE REVIEW

**Comment by carstenbauer** [comment]
The dataframe is certinaly internal. But, yeah, we should really mark the public API (the functions explicitly mentioned in `README.md`) by `public`, maybe even `export` some of them.

(With https://github.com/carstenbauer/SysInfo.jl/blob/main/src/utils.jl this can be done in a backwards compatible way.)

**Comment by carstenbauer** [comment]
Can you add a test (even if it just tests that the function exists and takes in a string)?

**Comment by roflmaostc** [comment]
Should I copy paste this into JuliaCon?

**Comment by carstenbauer** [comment]
> Should I copy paste this into JuliaCon?

Sure, but I think this should be separate PR (after this one).

**Comment by carstenbauer** [comment]
Minor thing: `search_abstract` should probably better be a keyword argument. Otherwise, this looks good to me!

**Comment by roflmaostc** [comment]
Isn't it one?

**Comment by carstenbauer** [comment]
Oh, my bad, I just looked at https://github.com/JuliaCon/JuliaCon.jl/pull/40/files#diff-3b9314a6f9f2d7eec1d0ef69fa76cfabafdbe6d0df923768f9ec32f27a249c63R67.

**Pull request merged**
